ADD_CONTACT = 'add_contact'
REMOVE_CONTACT = 'remove_contact'
EDIT_CONTACT = 'edit_contact'
FIND_CONTACT = 'find_contact'
SHOW_BIRTHDAY = 'show_birthday'
SORT_FILES = 'sort_files'
EXIT = 'exit'
CLOSE = 'close'